# Generated by Django 3.0.7 on 2020-07-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LYF',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('OwnerName', models.CharField(max_length=50)),
                ('RoomTitle', models.CharField(max_length=100)),
                ('OwnerEmail', models.CharField(max_length=50)),
                ('OwnerNumber', models.CharField(max_length=15)),
                ('OwnerPostalCode', models.CharField(max_length=6)),
                ('OwnerAddress', models.TextField()),
                ('OwnerPrice', models.IntegerField(default=0)),
                ('OwnerRooms', models.CharField(max_length=15)),
                ('Flooring', models.CharField(max_length=20)),
                ('Floor', models.CharField(max_length=4)),
                ('TOB', models.CharField(max_length=50)),
                ('Hall', models.ImageField(default='', upload_to='Rooms/Images')),
                ('Bedroom_1', models.ImageField(default='', upload_to='Rooms/Images')),
                ('Bedroom_2', models.ImageField(default='', upload_to='Rooms/Images')),
                ('Bedroom_3', models.ImageField(default='', upload_to='Rooms/Images')),
                ('Kitchen', models.ImageField(default='', upload_to='Rooms/Images')),
                ('Bathroom', models.ImageField(default='', upload_to='Rooms/Images')),
            ],
        ),
    ]
