# Generated by Django 3.0.7 on 2020-07-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRS', '0002_lyf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyf',
            name='Bathroom',
            field=models.ImageField(upload_to='Rooms/Images'),
        ),
        migrations.AlterField(
            model_name='lyf',
            name='Bedroom_1',
            field=models.ImageField(upload_to='Rooms/Images'),
        ),
        migrations.AlterField(
            model_name='lyf',
            name='Bedroom_2',
            field=models.ImageField(upload_to='Rooms/Images'),
        ),
        migrations.AlterField(
            model_name='lyf',
            name='Bedroom_3',
            field=models.ImageField(upload_to='Rooms/Images'),
        ),
        migrations.AlterField(
            model_name='lyf',
            name='Hall',
            field=models.ImageField(upload_to='Rooms/Images'),
        ),
        migrations.AlterField(
            model_name='lyf',
            name='Kitchen',
            field=models.ImageField(upload_to='Rooms/Images'),
        ),
    ]
